dist: trusty
language: python

python:
    - 3.6

install:
    - pip install coveralls pytest==3.6 pytest-cov black==20.8b1
    - pip install pyspark lxml requests beautifulsoup4 pandas numpy pyarrow

script:
    - export PYTHONPATH=${PYTHONPATH}:${PWD}
    - export PYSPARK_PYTHON=~/virtualenv/python3.6/bin/python
    - black --check src/

after_success:
    - coveralls
